### ISSUE TITLE
Starting an encounter without any monsters exits the encounter

### ISSUE THREAD

**Issue by PhamJay** [Cetzcher/dndtools#1]
Unhandled error:
"error while reading input
list index out of range"

1.Create an Encounter without adding monster
2. Start the Encounter
3. The error occurs

Windows 10/Python 3.7.2

**Comment by Corvisoft** [comment]
Encounters without any monsters don't make sense so i think this is behavior is intended, feel free to discuss

**Comment by PhamJay** [comment]
True but this could be fixed relatively easy and would prevent users accidentally creating empty ones

**Comment by Corvisoft** [comment]
creating empty ones is fixed now, so the user should not be able to do so anymore. close if you want
