### ISSUE TITLE
Initiative is kinda useless as long as players cannot be added

### ISSUE THREAD

**Issue by PhamJay** [Cetzcher/dndtools#4]

**Comment by Corvisoft** [comment]
you are supposed to create their characters and add them to the encounter beforehand but i agree we should have a ADD option in the encounter input module that just adds a blank creature OR a creature in the monsterlist

**Comment by Corvisoft** [comment]
we can now enter new creatures by calling add so all we have to do is create the hero JSON beforehand aka add player max HP and player AC as well as player name and we can then add them to the encoutners

**Comment by PhamJay** [comment]
Perfect
