### ISSUE TITLE
Initiative input-handling is bugged

### ISSUE THREAD

**Issue by PhamJay** [Cetzcher/dndtools#6]
While assigning initiative, when typing something that isn't a number > 0, the option to reinput is given. However, whatever is then written, the result will be "None", resulting in the encounter ending/not working

Errors:
- If multiple enemies, upon pressing "yes":
error while reading input
'<' not supported between instances of 'NoneType' and 'int'

-if only one enemy:
error while reading input
unsupported format string passed to NoneType.__format__

**Comment by Corvisoft** [comment]
fixed in upcoming commit
